//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtualMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.PedidosItems = new HashSet<PedidosItem>();
        }
    
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public string Imagen { get; set; }
        public string Detalles { get; set; }
        public int codigo_proveedor { get; set; }
        public int stock { get; set; }
        

         public HttpPostedFileBase ImageFile { get; set; }   
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosItem> PedidosItems { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
